---
- hosts: localhost
  connection: local
  strategy: debug

  vars_files:
    - defaults/main.yml

  tasks:
    - include: tasks/homebrew.yml
    - include: tasks/atom.yml
    - include: tasks/dotfiles.yml
    - include: tasks/osx.yml
